// Generated by Apple Swift version 4.2 (swiftlang-1000.11.37.1 clang-1000.11.45.1)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <objc/NSObject.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if __has_feature(modules)
@import Foundation;
@import ObjectiveC;
@import UIKit;
@import WebKit;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="PGW",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

typedef SWIFT_ENUM(NSInteger, APIEnvironment, closed) {
  APIEnvironmentPRODUCTION = 0,
  APIEnvironmentPRODUCTION_INDONESIA = 1,
  APIEnvironmentSANDBOX = 2,
};


SWIFT_CLASS("_TtC3PGW15APIResponseCode")
@interface APIResponseCode : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull API_SUCCESS;)
+ (NSString * _Nonnull)API_SUCCESS SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull TRANSACTION_AUTHENTICATE;)
+ (NSString * _Nonnull)TRANSACTION_AUTHENTICATE SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull TRANSACTION_PAYMENT_SLIP;)
+ (NSString * _Nonnull)TRANSACTION_PAYMENT_SLIP SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull TRANSACTION_COMPLETED;)
+ (NSString * _Nonnull)TRANSACTION_COMPLETED SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC3PGW9BaseModel")
@interface BaseModel : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class AgentChannel;

SWIFT_CLASS("_TtC3PGW5Agent")
@interface Agent : BaseModel
@property (nonatomic, readonly, copy) NSString * _Null_unspecified code;
@property (nonatomic, readonly, copy) NSString * _Null_unspecified name;
@property (nonatomic, readonly, copy) NSString * _Null_unspecified logoUrl;
@property (nonatomic, readonly, copy) NSArray<AgentChannel *> * _Null_unspecified agentChannels;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC3PGW12AgentChannel")
@interface AgentChannel : BaseModel
@property (nonatomic, readonly, copy) NSString * _Null_unspecified code;
@property (nonatomic, readonly, copy) NSString * _Null_unspecified name;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC3PGW11AgentOption")
@interface AgentOption : BaseModel
@property (nonatomic, readonly, copy) NSString * _Null_unspecified type;
@property (nonatomic, readonly, copy) NSArray<Agent *> * _Null_unspecified agents;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC3PGW13AgentTypeCode")
@interface AgentTypeCode : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull BANK;)
+ (NSString * _Nonnull)BANK SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull KIOSK;)
+ (NSString * _Nonnull)KIOSK SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull COUNTER;)
+ (NSString * _Nonnull)COUNTER SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC3PGW23AlternativeOptionDetail")
@interface AlternativeOptionDetail : BaseModel
@property (nonatomic, readonly, copy) NSArray<AgentOption *> * _Null_unspecified agentOptions;
- (NSArray<Agent *> * _Nonnull)agentsWithAgentType:(NSString * _Nonnull)agentType SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC3PGW18AlternativePayment")
@interface AlternativePayment : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC3PGW25AlternativePaymentBuilder")
@interface AlternativePaymentBuilder : NSObject
- (nonnull instancetype)initWithAgentCode:(NSString * _Nonnull)agentCode channelCode:(NSString * _Nonnull)channelCode OBJC_DESIGNATED_INITIALIZER;
- (AlternativePaymentBuilder * _Nonnull)name:(NSString * _Nonnull)name SWIFT_WARN_UNUSED_RESULT;
- (AlternativePaymentBuilder * _Nonnull)email:(NSString * _Nonnull)email SWIFT_WARN_UNUSED_RESULT;
- (AlternativePaymentBuilder * _Nonnull)mobileNumber:(NSString * _Nonnull)number SWIFT_WARN_UNUSED_RESULT;
- (AlternativePayment * _Nonnull)build SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end

@class Plan;

SWIFT_CLASS("_TtC3PGW4Bank")
@interface Bank : BaseModel
@property (nonatomic, readonly, copy) NSString * _Null_unspecified name;
@property (nonatomic, readonly, copy) NSString * _Null_unspecified shortName;
@property (nonatomic, readonly, copy) NSString * _Null_unspecified terms;
@property (nonatomic, readonly, copy) NSArray<NSString *> * _Null_unspecified bins;
@property (nonatomic, readonly, copy) NSString * _Null_unspecified logoUrl;
@property (nonatomic, readonly, copy) NSString * _Null_unspecified promoUrl;
@property (nonatomic, readonly, copy) NSArray<Plan *> * _Null_unspecified plans;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC3PGW22BaseCardPaymentBuilder")
@interface BaseCardPaymentBuilder : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end



SWIFT_CLASS("_TtC3PGW11BaseRequest")
@interface BaseRequest : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC3PGW12BaseResponse")
@interface BaseResponse : BaseModel
@property (nonatomic, readonly, copy) NSString * _Null_unspecified version;
@property (nonatomic, readonly, copy) NSString * _Null_unspecified responseCode;
@property (nonatomic, readonly, copy) NSString * _Null_unspecified responseDescription;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class CreditCardPayment;

SWIFT_CLASS("_TtC3PGW23CardTokenPaymentBuilder")
@interface CardTokenPaymentBuilder : BaseCardPaymentBuilder
- (nonnull instancetype)initWithCardToken:(NSString * _Nonnull)cardToken OBJC_DESIGNATED_INITIALIZER;
- (CardTokenPaymentBuilder * _Nonnull)securityCode:(NSString * _Nonnull)securityCode SWIFT_WARN_UNUSED_RESULT;
- (CardTokenPaymentBuilder * _Nonnull)expiryMonth:(NSInteger)month SWIFT_WARN_UNUSED_RESULT;
- (CardTokenPaymentBuilder * _Nonnull)expiryYear:(NSInteger)year SWIFT_WARN_UNUSED_RESULT;
- (CardTokenPaymentBuilder * _Nonnull)email:(NSString * _Nonnull)email SWIFT_WARN_UNUSED_RESULT;
- (CardTokenPaymentBuilder * _Nonnull)mobileNumber:(NSString * _Nonnull)mobileNumber SWIFT_WARN_UNUSED_RESULT;
- (CardTokenPaymentBuilder * _Nonnull)cardToken:(NSString * _Nonnull)cardToken SWIFT_WARN_UNUSED_RESULT;
- (CreditCardPayment * _Nonnull)build SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC3PGW8CardType")
@interface CardType : BaseModel
@property (nonatomic, readonly, copy) NSString * _Null_unspecified code;
@property (nonatomic, readonly, copy) NSString * _Null_unspecified name;
@property (nonatomic, readonly, copy) NSString * _Null_unspecified iconUrl;
@property (nonatomic, readonly, copy) NSArray<NSString *> * _Null_unspecified prefixes;
@property (nonatomic, readonly) NSInteger minLength;
@property (nonatomic, readonly) NSInteger maxLength;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC3PGW12CardTypeCode")
@interface CardTypeCode : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull VISA;)
+ (NSString * _Nonnull)VISA SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull MASTER_CARD;)
+ (NSString * _Nonnull)MASTER_CARD SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull AMEX;)
+ (NSString * _Nonnull)AMEX SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull DINERS_CLUB;)
+ (NSString * _Nonnull)DINERS_CLUB SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull DISCOVER;)
+ (NSString * _Nonnull)DISCOVER SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull JCB;)
+ (NSString * _Nonnull)JCB SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull KBZ;)
+ (NSString * _Nonnull)KBZ SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull MPU;)
+ (NSString * _Nonnull)MPU SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull UNION_PAY;)
+ (NSString * _Nonnull)UNION_PAY SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC3PGW7Channel")
@interface Channel : BaseModel
@property (nonatomic, readonly, copy) NSString * _Null_unspecified name;
@property (nonatomic, readonly, copy) NSString * _Null_unspecified iconUrl;
- (NSString * _Nonnull)paymentChannel SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC3PGW9Constants")
@interface Constants : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end




@interface Constants (SWIFT_EXTENSION(PGW))
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull JSON_NAME_ID;)
+ (NSString * _Nonnull)JSON_NAME_ID SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull JSON_NAME_ENCRYPTED_CARD_DATA;)
+ (NSString * _Nonnull)JSON_NAME_ENCRYPTED_CARD_DATA SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull JSON_NAME_CARD_TOKEN;)
+ (NSString * _Nonnull)JSON_NAME_CARD_TOKEN SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull JSON_NAME_INSTALLMENT_PERIOD;)
+ (NSString * _Nonnull)JSON_NAME_INSTALLMENT_PERIOD SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull JSON_NAME_VERSION;)
+ (NSString * _Nonnull)JSON_NAME_VERSION SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull JSON_NAME_PAYMENT_TOKEN;)
+ (NSString * _Nonnull)JSON_NAME_PAYMENT_TOKEN SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull JSON_NAME_MERCHANT_ID;)
+ (NSString * _Nonnull)JSON_NAME_MERCHANT_ID SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull JSON_NAME_PAYMENT_CHANNEL;)
+ (NSString * _Nonnull)JSON_NAME_PAYMENT_CHANNEL SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull JSON_NAME_PAYMENT_PARAMS;)
+ (NSString * _Nonnull)JSON_NAME_PAYMENT_PARAMS SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull JSON_NAME_CARD_DETAILS;)
+ (NSString * _Nonnull)JSON_NAME_CARD_DETAILS SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull JSON_NAME_STORE_CARD;)
+ (NSString * _Nonnull)JSON_NAME_STORE_CARD SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull JSON_NAME_INSTALLMENT_TRANSACTION;)
+ (NSString * _Nonnull)JSON_NAME_INSTALLMENT_TRANSACTION SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull JSON_NAME_CARD_HOLDER_EMAIL;)
+ (NSString * _Nonnull)JSON_NAME_CARD_HOLDER_EMAIL SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull JSON_NAME_MOBILE_NO;)
+ (NSString * _Nonnull)JSON_NAME_MOBILE_NO SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull JSON_NAME_PAN;)
+ (NSString * _Nonnull)JSON_NAME_PAN SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull JSON_NAME_EXPIRY;)
+ (NSString * _Nonnull)JSON_NAME_EXPIRY SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull JSON_NAME_EXPIRY_MONTH;)
+ (NSString * _Nonnull)JSON_NAME_EXPIRY_MONTH SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull JSON_NAME_EXPIRY_YEAR;)
+ (NSString * _Nonnull)JSON_NAME_EXPIRY_YEAR SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull JSON_NAME_SECURITY_CODE;)
+ (NSString * _Nonnull)JSON_NAME_SECURITY_CODE SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull JSON_NAME_PAN_BANK;)
+ (NSString * _Nonnull)JSON_NAME_PAN_BANK SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull JSON_NAME_PAN_COUNTRY;)
+ (NSString * _Nonnull)JSON_NAME_PAN_COUNTRY SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull JSON_NAME_CARD_HOLDER_NAME;)
+ (NSString * _Nonnull)JSON_NAME_CARD_HOLDER_NAME SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull JSON_NAME_AGENT_CODE;)
+ (NSString * _Nonnull)JSON_NAME_AGENT_CODE SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull JSON_NAME_CHANNEL_CODE;)
+ (NSString * _Nonnull)JSON_NAME_CHANNEL_CODE SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull JSON_NAME_CODE;)
+ (NSString * _Nonnull)JSON_NAME_CODE SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull JSON_NAME_BINS;)
+ (NSString * _Nonnull)JSON_NAME_BINS SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull JSON_NAME_CARD_TYPES;)
+ (NSString * _Nonnull)JSON_NAME_CARD_TYPES SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull JSON_NAME_RESP_CODE;)
+ (NSString * _Nonnull)JSON_NAME_RESP_CODE SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull JSON_NAME_RESP_DESC;)
+ (NSString * _Nonnull)JSON_NAME_RESP_DESC SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull JSON_NAME_CREDIT_CARD;)
+ (NSString * _Nonnull)JSON_NAME_CREDIT_CARD SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull JSON_NAME_PREFIXES;)
+ (NSString * _Nonnull)JSON_NAME_PREFIXES SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull JSON_NAME_NAME;)
+ (NSString * _Nonnull)JSON_NAME_NAME SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull JSON_NAME_ICON_URL;)
+ (NSString * _Nonnull)JSON_NAME_ICON_URL SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull JSON_NAME_MIN_LENGTH;)
+ (NSString * _Nonnull)JSON_NAME_MIN_LENGTH SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull JSON_NAME_MAX_LENGTH;)
+ (NSString * _Nonnull)JSON_NAME_MAX_LENGTH SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull JSON_NAME_MERCHANT_DETAILS;)
+ (NSString * _Nonnull)JSON_NAME_MERCHANT_DETAILS SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull JSON_NAME_TRANSACTION_DETAILS;)
+ (NSString * _Nonnull)JSON_NAME_TRANSACTION_DETAILS SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull JSON_NAME_PAYMENT_CHANNELS;)
+ (NSString * _Nonnull)JSON_NAME_PAYMENT_CHANNELS SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull JSON_NAME_INSTALLMENT;)
+ (NSString * _Nonnull)JSON_NAME_INSTALLMENT SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull JSON_NAME_BANKS;)
+ (NSString * _Nonnull)JSON_NAME_BANKS SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull JSON_NAME_SHORT_NAME;)
+ (NSString * _Nonnull)JSON_NAME_SHORT_NAME SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull JSON_NAME_TERMS;)
+ (NSString * _Nonnull)JSON_NAME_TERMS SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull JSON_NAME_LOGO_URL;)
+ (NSString * _Nonnull)JSON_NAME_LOGO_URL SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull JSON_NAME_PROMO_URL;)
+ (NSString * _Nonnull)JSON_NAME_PROMO_URL SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull JSON_NAME_PLANS;)
+ (NSString * _Nonnull)JSON_NAME_PLANS SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull JSON_NAME_PERIOD;)
+ (NSString * _Nonnull)JSON_NAME_PERIOD SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull JSON_NAME_INTEREST_TYPE;)
+ (NSString * _Nonnull)JSON_NAME_INTEREST_TYPE SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull JSON_NAME_INTEREST_RATE;)
+ (NSString * _Nonnull)JSON_NAME_INTEREST_RATE SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull JSON_NAME_MONTHLY_AMOUNT;)
+ (NSString * _Nonnull)JSON_NAME_MONTHLY_AMOUNT SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull JSON_NAME_MONTHLY_INTEREST;)
+ (NSString * _Nonnull)JSON_NAME_MONTHLY_INTEREST SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull JSON_NAME_CURRENCY_CODE;)
+ (NSString * _Nonnull)JSON_NAME_CURRENCY_CODE SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull JSON_NAME_LABEL;)
+ (NSString * _Nonnull)JSON_NAME_LABEL SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull JSON_NAME_AMOUNT;)
+ (NSString * _Nonnull)JSON_NAME_AMOUNT SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull JSON_NAME_INVOICE_NO;)
+ (NSString * _Nonnull)JSON_NAME_INVOICE_NO SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull JSON_NAME_MERCHANT_NAME;)
+ (NSString * _Nonnull)JSON_NAME_MERCHANT_NAME SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull JSON_NAME_ADDRESS;)
+ (NSString * _Nonnull)JSON_NAME_ADDRESS SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull JSON_NAME_EMAIL;)
+ (NSString * _Nonnull)JSON_NAME_EMAIL SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull JSON_NAME_DESCRIPTION;)
+ (NSString * _Nonnull)JSON_NAME_DESCRIPTION SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull JSON_NAME_TRANSACTION_ID;)
+ (NSString * _Nonnull)JSON_NAME_TRANSACTION_ID SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull JSON_NAME_REDIRECT_URL;)
+ (NSString * _Nonnull)JSON_NAME_REDIRECT_URL SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull JSON_NAME_ALTERNATIVE_PAYMENT;)
+ (NSString * _Nonnull)JSON_NAME_ALTERNATIVE_PAYMENT SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull JSON_NAME_OPTIONS;)
+ (NSString * _Nonnull)JSON_NAME_OPTIONS SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull JSON_NAME_TYPE;)
+ (NSString * _Nonnull)JSON_NAME_TYPE SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull JSON_NAME_AGENTS;)
+ (NSString * _Nonnull)JSON_NAME_AGENTS SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull JSON_NAME_CHANNELS;)
+ (NSString * _Nonnull)JSON_NAME_CHANNELS SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull JSON_NAME_SLIP_URL;)
+ (NSString * _Nonnull)JSON_NAME_SLIP_URL SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull JSON_NAME_SIGNATURE;)
+ (NSString * _Nonnull)JSON_NAME_SIGNATURE SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull JSON_NAME_RETURN_URL;)
+ (NSString * _Nonnull)JSON_NAME_RETURN_URL SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS("_TtC3PGW22CreditCardOptionDetail")
@interface CreditCardOptionDetail : BaseModel
@property (nonatomic, readonly, copy) NSArray<NSString *> * _Null_unspecified bins;
@property (nonatomic, readonly, copy) NSArray<CardType *> * _Null_unspecified cardTypes;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC3PGW17CreditCardPayment")
@interface CreditCardPayment : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC3PGW24CreditCardPaymentBuilder")
@interface CreditCardPaymentBuilder : BaseCardPaymentBuilder
- (nonnull instancetype)initWithPan:(NSString * _Nonnull)pan OBJC_DESIGNATED_INITIALIZER;
- (CreditCardPaymentBuilder * _Nonnull)securityCode:(NSString * _Nonnull)securityCode SWIFT_WARN_UNUSED_RESULT;
- (CreditCardPaymentBuilder * _Nonnull)expiryMonth:(NSInteger)month SWIFT_WARN_UNUSED_RESULT;
- (CreditCardPaymentBuilder * _Nonnull)expiryYear:(NSInteger)year SWIFT_WARN_UNUSED_RESULT;
- (CreditCardPaymentBuilder * _Nonnull)bank:(NSString * _Nonnull)bank SWIFT_WARN_UNUSED_RESULT;
- (CreditCardPaymentBuilder * _Nonnull)country:(NSString * _Nonnull)country SWIFT_WARN_UNUSED_RESULT;
- (CreditCardPaymentBuilder * _Nonnull)name:(NSString * _Nonnull)name SWIFT_WARN_UNUSED_RESULT;
- (CreditCardPaymentBuilder * _Nonnull)email:(NSString * _Nonnull)email SWIFT_WARN_UNUSED_RESULT;
- (CreditCardPaymentBuilder * _Nonnull)mobileNumber:(NSString * _Nonnull)mobileNumber SWIFT_WARN_UNUSED_RESULT;
- (CreditCardPaymentBuilder * _Nonnull)storeCard:(BOOL)storeCard SWIFT_WARN_UNUSED_RESULT;
- (CreditCardPayment * _Nonnull)build SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC3PGW23InstallmentOptionDetail")
@interface InstallmentOptionDetail : BaseModel
@property (nonatomic, readonly, copy) NSArray<Bank *> * _Null_unspecified banks;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC3PGW18InstallmentPayment")
@interface InstallmentPayment : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC3PGW25InstallmentPaymentBuilder")
@interface InstallmentPaymentBuilder : NSObject
- (nonnull instancetype)initWithPeriod:(NSInteger)period OBJC_DESIGNATED_INITIALIZER;
- (InstallmentPaymentBuilder * _Nonnull)withCreditCardPayment:(CreditCardPayment * _Nonnull)creditCardPayment SWIFT_WARN_UNUSED_RESULT;
- (InstallmentPayment * _Nonnull)build SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC3PGW16InterestTypeCode")
@interface InterestTypeCode : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull NONE;)
+ (NSString * _Nonnull)NONE SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull CUSTOMER;)
+ (NSString * _Nonnull)CUSTOMER SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull MERCHANT;)
+ (NSString * _Nonnull)MERCHANT SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC3PGW14MerchantDetail")
@interface MerchantDetail : BaseModel
@property (nonatomic, readonly, copy) NSString * _Null_unspecified name;
@property (nonatomic, readonly, copy) NSString * _Nullable address;
@property (nonatomic, readonly, copy) NSString * _Nullable iconUrl;
@property (nonatomic, readonly, copy) NSString * _Nullable email;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class TransactionResultResponse;
@class NSError;

SWIFT_CLASS("_TtC3PGW22PGWBaseWebViewDelegate")
@interface PGWBaseWebViewDelegate : NSObject
- (nonnull instancetype)initWithSuccess:(void (^ _Nonnull)(TransactionResultResponse * _Nonnull))success failure:(void (^ _Nonnull)(NSError * _Nonnull))failure OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end

@class PGWSDK;

SWIFT_CLASS("_TtC3PGW13PGWSDKBuilder")
@interface PGWSDKBuilder : NSObject
@property (nonatomic, readonly) enum APIEnvironment apiEnvironment;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
- (PGWSDKBuilder * _Nonnull)apiEnvironment:(enum APIEnvironment)apiEnvironment SWIFT_WARN_UNUSED_RESULT;
- (PGWSDKBuilder * _Nonnull)merchantID:(NSString * _Nonnull)merchantID SWIFT_WARN_UNUSED_RESULT;
- (PGWSDKBuilder * _Nonnull)enableLog:(BOOL)enableLog SWIFT_WARN_UNUSED_RESULT;
- (PGWSDK * _Nullable)initialize SWIFT_WARN_UNUSED_RESULT;
@end

@class PaymentOptionRequest;
@class PaymentOptionResponse;
@class PaymentOptionDetailRequest;
@class PaymentOptionDetailResponse;
@class TransactionRequest;

SWIFT_CLASS("_TtC3PGW6PGWSDK")
@interface PGWSDK : PGWSDKBuilder
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) PGWSDK * _Nonnull shared;)
+ (PGWSDK * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
+ (PGWSDKBuilder * _Nonnull)builder SWIFT_WARN_UNUSED_RESULT;
- (void)paymentOptionWithPaymentOptionRequest:(PaymentOptionRequest * _Nonnull)request success:(void (^ _Nonnull)(PaymentOptionResponse * _Nonnull))success failure:(void (^ _Nonnull)(NSError * _Nonnull))failure;
- (void)paymentOptionDetailWithPaymentOptionDetailRequest:(PaymentOptionDetailRequest * _Nonnull)request success:(void (^ _Nonnull)(PaymentOptionDetailResponse * _Nonnull))success failure:(void (^ _Nonnull)(NSError * _Nonnull))failure;
- (void)proceedTransactionWithTransactionRequest:(TransactionRequest * _Nonnull)request success:(void (^ _Nonnull)(TransactionResultResponse * _Nonnull))success failure:(void (^ _Nonnull)(NSError * _Nonnull))failure;
@end


@class UIWebView;

SWIFT_CLASS("_TtC3PGW20PGWUIWebViewDelegate")
@interface PGWUIWebViewDelegate : PGWBaseWebViewDelegate <UIWebViewDelegate>
- (BOOL)webView:(UIWebView * _Nonnull)webView shouldStartLoadWithRequest:(NSURLRequest * _Nonnull)request navigationType:(enum UIWebViewNavigationType)navigationType SWIFT_WARN_UNUSED_RESULT;
- (void)webViewDidFinishLoad:(UIWebView * _Nonnull)webView;
- (nonnull instancetype)initWithSuccess:(void (^ _Nonnull)(TransactionResultResponse * _Nonnull))success failure:(void (^ _Nonnull)(NSError * _Nonnull))failure OBJC_DESIGNATED_INITIALIZER;
@end

@class WKWebView;
@class WKNavigationAction;
@class WKNavigation;

SWIFT_CLASS("_TtC3PGW20PGWWKWebViewDelegate")
@interface PGWWKWebViewDelegate : PGWBaseWebViewDelegate <WKNavigationDelegate>
- (void)webView:(WKWebView * _Nonnull)webView decidePolicyForNavigationAction:(WKNavigationAction * _Nonnull)navigationAction decisionHandler:(void (^ _Nonnull)(WKNavigationActionPolicy))decisionHandler;
- (void)webView:(WKWebView * _Nonnull)webView didFinishNavigation:(WKNavigation * _Null_unspecified)navigation;
- (nonnull instancetype)initWithSuccess:(void (^ _Nonnull)(TransactionResultResponse * _Nonnull))success failure:(void (^ _Nonnull)(NSError * _Nonnull))failure OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC3PGW14PaymentChannel")
@interface PaymentChannel : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull NONE;)
+ (NSString * _Nonnull)NONE SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull CREDIT_CARD;)
+ (NSString * _Nonnull)CREDIT_CARD SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull INSTALLMENT;)
+ (NSString * _Nonnull)INSTALLMENT SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull ALTERNATIVE_PAYMENT;)
+ (NSString * _Nonnull)ALTERNATIVE_PAYMENT SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC3PGW26PaymentOptionDetailRequest")
@interface PaymentOptionDetailRequest : BaseRequest
@property (nonatomic, copy) NSString * _Null_unspecified paymentToken;
@property (nonatomic, copy) NSString * _Nonnull paymentChannel;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC3PGW27PaymentOptionDetailResponse")
@interface PaymentOptionDetailResponse : BaseResponse
@property (nonatomic, readonly, copy) NSString * _Null_unspecified paymentChannel;
@property (nonatomic, readonly, strong) CreditCardOptionDetail * _Nullable creditCardOptionDetails;
@property (nonatomic, readonly, strong) InstallmentOptionDetail * _Nullable installmentOptionDetail;
@property (nonatomic, readonly, strong) AlternativeOptionDetail * _Nullable alternativeOptionDetail;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC3PGW20PaymentOptionRequest")
@interface PaymentOptionRequest : BaseRequest
@property (nonatomic, copy) NSString * _Null_unspecified paymentToken;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class TransactionDetail;

SWIFT_CLASS("_TtC3PGW21PaymentOptionResponse")
@interface PaymentOptionResponse : BaseResponse
@property (nonatomic, readonly, copy) NSString * _Null_unspecified paymentToken;
@property (nonatomic, readonly, strong) MerchantDetail * _Null_unspecified merchantDetail;
@property (nonatomic, readonly, copy) NSArray<Channel *> * _Null_unspecified channels;
@property (nonatomic, readonly, strong) TransactionDetail * _Null_unspecified transactionDetail;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC3PGW4Plan")
@interface Plan : BaseModel
@property (nonatomic, readonly, copy) NSString * _Null_unspecified interestType;
@property (nonatomic, readonly, copy) NSString * _Null_unspecified currencyCode;
@property (nonatomic, readonly, copy) NSString * _Null_unspecified label;
@property (nonatomic, readonly) NSInteger period;
@property (nonatomic, readonly) double interestRate;
@property (nonatomic, readonly) double monthlyAmount;
@property (nonatomic, readonly) double monthlyInterest;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

typedef SWIFT_ENUM(NSInteger, SecurePayAPIEnvironment, closed) {
  SecurePayAPIEnvironmentPRODUCTION = 0,
  SecurePayAPIEnvironmentSANDBOX = 1,
};


SWIFT_CLASS("_TtC3PGW12SecurePaySDK")
@interface SecurePaySDK : NSObject
- (nonnull instancetype)initWithApiEnvironment:(enum SecurePayAPIEnvironment)apiEnvironment;
- (nonnull instancetype)initWithApiEnvironment:(enum SecurePayAPIEnvironment)apiEnvironment enableLog:(BOOL)enableLog OBJC_DESIGNATED_INITIALIZER;
- (NSString * _Nonnull)maskedCardNo SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)encryptWithCardNo:(NSString * _Nullable)cardNo expiryMonth:(NSInteger)expiryMonth expiryYear:(NSInteger)expiryYear securityCode:(NSString * _Nullable)securityCode SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC3PGW17TransactionDetail")
@interface TransactionDetail : BaseModel
@property (nonatomic, readonly, copy) NSString * _Null_unspecified amount;
@property (nonatomic, readonly, copy) NSString * _Null_unspecified currencyCode;
@property (nonatomic, readonly, copy) NSString * _Null_unspecified invoiceNo;
@property (nonatomic, readonly, copy) NSString * _Null_unspecified productDescription;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC3PGW18TransactionRequest")
@interface TransactionRequest : BaseRequest
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC3PGW25TransactionRequestBuilder")
@interface TransactionRequestBuilder : NSObject
- (nonnull instancetype)initWithPaymentToken:(NSString * _Nonnull)paymentToken OBJC_DESIGNATED_INITIALIZER;
- (TransactionRequestBuilder * _Nonnull)paymentToken:(NSString * _Nonnull)paymentToken SWIFT_WARN_UNUSED_RESULT;
- (TransactionRequestBuilder * _Nonnull)withCreditCardPayment:(CreditCardPayment * _Nonnull)creditCardPayment SWIFT_WARN_UNUSED_RESULT;
- (TransactionRequestBuilder * _Nonnull)withInstallmentPayment:(InstallmentPayment * _Nonnull)installmentPayment SWIFT_WARN_UNUSED_RESULT;
- (TransactionRequestBuilder * _Nonnull)withAlternativePayment:(AlternativePayment * _Nonnull)alternativePayment SWIFT_WARN_UNUSED_RESULT;
- (TransactionRequest * _Nonnull)build SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_DEPRECATED_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC3PGW25TransactionResultResponse")
@interface TransactionResultResponse : BaseResponse
@property (nonatomic, readonly, copy) NSString * _Null_unspecified paymentChannel;
@property (nonatomic, readonly, copy) NSString * _Nullable agentCode;
@property (nonatomic, readonly, copy) NSString * _Nullable channelCode;
@property (nonatomic, readonly, copy) NSString * _Nullable transactionID;
@property (nonatomic, readonly, copy) NSString * _Nullable redirectUrl;
@property (nonatomic, readonly, copy) NSString * _Nullable slipUrl;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#pragma clang diagnostic pop
